# Generated by Django 2.1.4 on 2018-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_text', models.CharField(max_length=200)),
                ('sub_date', models.DateTimeField(verbose_name='date submitted')),
                ('f_text', models.TextField()),
            ],
        ),
    ]
